---
steps:
  - label: ':hammer: Generate test logs'
    key: generate-logs
    command: |
      echo "Testing some formatted output:"
      echo -e "Line 1\nLine 2\tTabbed\rCarriage Return"
      echo "=== Some more test data ==="
  - label: ':mag: Retrieve and clean logs'
    depends_on: generate-logs
    command: |-
      # Method 1: Using curl + jq
      echo "--- Testing curl + jq method"
      STEP_URL="https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER"
      curl -H "Authorization: Bearer $API_TOKEN" "$${STEP_URL}/jobs/$BUILDKITE_JOB_ID/log" | jq -r '.content' > curl_cleaned_logs.txt
      cat curl_cleaned_logs.txt

      # Method 2: Using sed
      echo "--- Testing sed method"
      curl -H "Authorization: Bearer $API_TOKEN" "$${STEP_URL}/jobs/$BUILDKITE_JOB_ID/log" > raw_logs.txt
      sed -e 's/\\n/\n/g' -e 's/\\r//g' -e 's/\\t/\t/g' raw_logs.txt > sed_cleaned_logs.txt
      cat sed_cleaned_logs.txt

      # Method 3: Using buildkite-agent
      echo "--- Testing buildkite-agent method"
      if command -v buildkite-agent &> /dev/null; then
        buildkite-agent step get logs --step generate-logs > agent_cleaned_logs.txt
        cat agent_cleaned_logs.txt
      else
        echo "buildkite-agent command not found"
      fi
