---
steps:
  - label: ':hammer: Generate test logs'
    key: generate-logs
    command: |
      echo "What is my purpose?"
      echo ">You ~pass butter~ list directories."
      ls -lA /var/log/*.log
      cp /var/log/*.log .
    artifact_paths: ['*.log']
  - label: ':mag: Retrieve logs'
    depends_on: generate-logs
    command: |-
      echo "--- Testing buildkite-agent method"
      buildkite-agent artifact download *.log .
